version: 2.0

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0.2
    steps:
      - checkout
      - run: mvn test

  build:
    docker:
      - image: cimg/openjdk:17.0.2
    steps:
      - checkout
      - run: mvn test

workflows:
  version: 2
  test-then-build:
    jobs:
      - test
      - build:
          requires:
            - test
