version: 2.0

jobs:

  build:
    docker:
      - image: cimg/openjdk:17.0.2
    steps:
      - checkout
      - run: mvn compile

  test:
    docker:
      - image: cimg/openjdk:17.0.2
    steps:
      - checkout
      - run: mvn test

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
