version: 2.0

jobs:
  package:
    docker:
      - image: cimg/openjdk:17.0.2
    steps:
      - checkout
      - run: mvn package

workflows:
  version: 2

  build-then-test:
    jobs:
      - package
     
