version: 2.0

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0.2
    steps:
      - checkout
      - run: mvn test

  build:
    docker:
      - image: cimg/openjdk:17.0.2
    steps:
      - checkout
      - run: mvn build

workflows:
  version: 2
  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
